package com.shadows.liquiblq.data.hibernate.entities;

// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album")
public class Albums implements java.io.Serializable {

	private UUID id;
	private Date date;
	private String name;
	public Albums() {
	}

	public Albums(UUID id, Date date, String name) {
		this.id = id;
		this.date = date;
		this.name = name;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false, columnDefinition = "uuid")
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "name", nullable = false, length = 55)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
}
