// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1
package com.shadows.liquiblq.data.hibernate.entities;

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sessions generated by hbm2java
 */
@Entity
@Table(name = "sessions")
public class Sessions implements java.io.Serializable {

	private UUID id;
	private Integer userId;
	private boolean active;
	private Date dateCreated;

	public Sessions() {
	}

	public Sessions(UUID id, Integer userId, boolean active,
			Date dateCreated) {
		this.id = id;
		this.userId = userId;
		this.active = active;
		this.dateCreated = dateCreated;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, columnDefinition = "uuid")        
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer id) {
		this.userId = id;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 29)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
