package com.shadows.liquiblq.data.hibernate.entities;

// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Songs generated by hbm2java
 */
@Entity
@Table(name = "songs")
public class Songs implements Serializable {

	private UUID id;
	private UUID genre;
	private String name;
	private Date date;
	public Songs() {
	}

	@Id
	@GeneratedValue(generator = "uuid2")
        @GenericGenerator(name = "uuid2", strategy = "uuid2")
	@Column(name = "id", unique = true, nullable = false, columnDefinition = "uuid")
        @org.hibernate.annotations.Type(type="org.hibernate.type.PostgresUUIDType")
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

        @Column(name = "genre", nullable = false, columnDefinition = "uuid")
        @org.hibernate.annotations.Type(type="org.hibernate.type.PostgresUUIDType")
	public UUID getGenre() {
		return this.genre;
	}

	public void setGenre(UUID genre) {
		this.genre = genre;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


}
