package com.shadows.liquiblq.data.hibernate.entities;

// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SongsInAlbum generated by hbm2java
 */
@Entity
@Table(name = "songs_in_album")
public class SongsInAlbums implements java.io.Serializable {

	private int id;
	private Albums album;
	private Songs song;

	public SongsInAlbums() {
	}

	public SongsInAlbums(int id, Albums album, Songs songs) {
		this.id = id;
		this.album = album;
		this.song = songs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, columnDefinition = "serial")
        @SequenceGenerator(name="songs_in_album_id_seq",
                       sequenceName="songs_in_album_id_seq",
                       allocationSize=1)
        @GeneratedValue(strategy = GenerationType.SEQUENCE,
                    generator="songs_in_album_id_seq")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "album", nullable = false)
	public Albums getAlbum() {
		return this.album;
	}

	public void setAlbum(Albums album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "song", nullable = false)
	public Songs getSong() {
		return this.song;
	}

	public void setSong(Songs songs) {
		this.song = songs;
	}

}
