package com.shadows.liquiblq.data.entitys;

// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre")
public class Genre implements java.io.Serializable {

	private UUID id;
	private String name;
	
	public Genre() {
	}

	public Genre(UUID id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 55)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

}
