// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre")
public class Genre implements java.io.Serializable {

	private Serializable id;
	private String name;
	private Set<Songs> songses = new HashSet<Songs>(0);

	public Genre() {
	}

	public Genre(Serializable id, String name) {
		this.id = id;
		this.name = name;
	}

	public Genre(Serializable id, String name, Set<Songs> songses) {
		this.id = id;
		this.name = name;
		this.songses = songses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 55)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Songs> getSongses() {
		return this.songses;
	}

	public void setSongses(Set<Songs> songses) {
		this.songses = songses;
	}

}
