package com.shadows.liquiblq.data.entitys;

// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Songs generated by hbm2java
 */
@Entity
@Table(name = "songs")
public class Songs implements java.io.Serializable {

	private Serializable id;
	private Genre genre;
	private String name;
	private Date date;
	private Set<SongsInAlbum> songsInAlbums = new HashSet<SongsInAlbum>(0);

	public Songs() {
	}

	public Songs(Serializable id, Genre genre, String name, Date date) {
		this.id = id;
		this.genre = genre;
		this.name = name;
		this.date = date;
	}

	public Songs(Serializable id, Genre genre, String name, Date date,
			Set<SongsInAlbum> songsInAlbums) {
		this.id = id;
		this.genre = genre;
		this.name = name;
		this.date = date;
		this.songsInAlbums = songsInAlbums;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genre", nullable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@Column(name = "name", nullable = false, length = 55)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "songs")
	public Set<SongsInAlbum> getSongsInAlbums() {
		return this.songsInAlbums;
	}

	public void setSongsInAlbums(Set<SongsInAlbum> songsInAlbums) {
		this.songsInAlbums = songsInAlbums;
	}

}
