package com.shadows.liquiblq.data.entitys;

// default package
// Generated 09-Oct-2015 13:21:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SongsInAlbum generated by hbm2java
 */
@Entity
@Table(name = "songs_in_album")
public class SongsInAlbum implements java.io.Serializable {

	private int id;
	private Album album;
	private Songs songs;

	public SongsInAlbum() {
	}

	public SongsInAlbum(int id, Album album, Songs songs) {
		this.id = id;
		this.album = album;
		this.songs = songs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "album", nullable = false)
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song", nullable = false)
	public Songs getSongs() {
		return this.songs;
	}

	public void setSongs(Songs songs) {
		this.songs = songs;
	}

}
