package com.shadows.liquiblq.data.models;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private int id;
	private String email;
	private String password;
	private String salt;
	private String name;
	private Date dateRegistered;
	private Set<Sessions> sessionses = new HashSet<Sessions>(0);

	public Users() {
	}

	public Users(int id, String email, String password, String salt,
			Date dateRegistered) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.dateRegistered = dateRegistered;
	}

	public Users(int id, String email, String password, String salt,
			String name, Date dateRegistered, Set<Sessions> sessionses) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.name = name;
		this.dateRegistered = dateRegistered;
		this.sessionses = sessionses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 55)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", nullable = false, length = 5)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_registered", nullable = false, length = 29)
	public Date getDateRegistered() {
		return this.dateRegistered;
	}

	public void setDateRegistered(Date dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Sessions> getSessionses() {
		return this.sessionses;
	}

	public void setSessionses(Set<Sessions> sessionses) {
		this.sessionses = sessionses;
	}

}
